package example

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestHandler
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPEvent
import com.amazonaws.services.lambda.runtime.events.APIGatewayV2HTTPResponse

// Handler value: example.HandlerApiGateway
class HandlerApiGatewayV2 : RequestHandler<APIGatewayV2HTTPEvent, APIGatewayV2HTTPResponse> {
    override fun handleRequest(event: APIGatewayV2HTTPEvent, context: Context): APIGatewayV2HTTPResponse {
        val logger = context.logger
        logger.log("EVENT TYPE: " + event.javaClass.toString())
        val response = APIGatewayV2HTTPResponse()
        response.isBase64Encoded = false
        response.statusCode = 200
        val headers = HashMap<String, String>()
        headers["Content-Type"] = "text/html"
        response.headers = headers
        val body = if (event.body != null) event.body else "Empty body"
        response.body = "<!DOCTYPE html><html><head><title>" + body + "</title></head><body>" +
                "<h1>Welcome</h1><p>Page generated by a Lambda function.</p>" + "</body></html>"
        return response
    }
}
